version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jforum-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jforum
      MYSQL_USER: jforum
      MYSQL_PASSWORD: jforum
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jforum-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  jforum-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jforum-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jforum
      - SPRING_DATASOURCE_USERNAME=jforum
      - SPRING_DATASOURCE_PASSWORD=jforum
      - JWT_SECRET=jforumSecretKey123456789012345678901234567890
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads
    networks:
      - jforum-network

volumes:
  mysql-data:
  uploads:

networks:
  jforum-network:
    driver: bridge