spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jforum
    username: jforum
    password: jforum
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    net.jforum: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true