spring:
  application:
    name: jforum-spring
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
        
server:
  servlet:
    context-path: /api
  port: 8080
  
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:jforumSecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  
# Attachment Configuration
attachment:
  upload-dir: uploads
  max-size: 5242880 # 5MB
  allowed-types: image/jpeg,image/png,image/gif,application/pdf,application/zip
  
# Logging
logging:
  level:
    root: INFO
    net.jforum: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO